# -*- coding: utf-8 -*-
"""mlhw1q4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GdHiX44yQctclEoZ6ZUiRgYKIJg-mdaT

Part (a) :

define an function to read each document and convert it into a vector of words and obtain appearance time of each word and tf of each word in each .txt document
"""

import string
#upload text to colab first

def preprocess(x):
  with open (x, 'r+') as f:
    filestr=f.read()
  
  #convert words into a vector :
  words = ''.join(c for c in filestr if c not in string.punctuation)#remove punctuation
  words = words.lower()#convert all letters to lowercase
  words = words.split()#split words by blank or \n
  #print(words)
  
  #appearance time of each word :
  count = {} 
  for n in range(0,len(words)):
    count[ words[n] ] = words.count( words[n] )
  #print(count)
  
  #tf of each word :
  tf = {}
  for k,v in count.items():
    tf[k] =  v / len(words) 
  
  return [count,tf]

"""Part (b) :

b1. put appearance counter of words and tf of words in every doucument respectively into two lists : counter , tfdic
"""

counter = []
tfdic = []
i = 1 
for n in ['/d_query.txt','/d1.txt','/d2.txt','/d3.txt','/d4.txt','/d5.txt']:
  counter.append( preprocess(n)[0] )
  tfdic.append( preprocess(n)[1] )
for i in range(1,6): 
  print("appearance time of words in d"+str(i)+":",counter[i])
  print("time frequency of words in d"+str(i)+":",tfdic[i])
print("appearance time of words in d_query:",counter[0])
print("time frequency of words in d_query:",tfdic[0])

"""b2. obtain idf of each words in every document and put them together into one list : tfdic"""

import math

idfdic = []
for n in range(0,6):
  idf = {}
  for k,v in counter[n].items():
    c=0
    for m in range(0,6):
      if k in counter[m] :
        c = c + 1
    if c == 0:
      c = c + 1 #in case c == 0    
    idf[k] = math.log10(6 / c )
  idfdic.append(idf)  

for n in range(1,6):
  print("inverse document frequency of words in d"+str(n)+":",tfdic[i])
print("inverse document frequency of words in d_query:",tfdic[0])

"""b3. obtain tf-idf of each words in every document and put them together into one list : tfidfdic"""

tfidfdic = []
for n in range(0,6):
  tfidf = {}
  for k,v in tfdic[n].items():
    tfidf[k] = tfdic[n][k] * idfdic[n][k]
  tfidfdic.append(tfidf)

for n in range(1,6):
  print("tf-idf of words in d"+str(n)+":",tfidfdic[i])
print("tf-idf of words in d_query:",tfidfdic[0])

"""Part (c) :"""